/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as FreelancersIndexRouteImport } from './routes/freelancers.index'
import { Route as FreelancersIdRouteImport } from './routes/freelancers.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelancersIndexRoute = FreelancersIndexRouteImport.update({
  id: '/freelancers/',
  path: '/freelancers/',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelancersIdRoute = FreelancersIdRouteImport.update({
  id: '/freelancers/$id',
  path: '/freelancers/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/projects': typeof ProjectsRoute
  '/freelancers/$id': typeof FreelancersIdRoute
  '/freelancers/': typeof FreelancersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/projects': typeof ProjectsRoute
  '/freelancers/$id': typeof FreelancersIdRoute
  '/freelancers': typeof FreelancersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/projects': typeof ProjectsRoute
  '/freelancers/$id': typeof FreelancersIdRoute
  '/freelancers/': typeof FreelancersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categories'
    | '/leaderboard'
    | '/projects'
    | '/freelancers/$id'
    | '/freelancers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories'
    | '/leaderboard'
    | '/projects'
    | '/freelancers/$id'
    | '/freelancers'
  id:
    | '__root__'
    | '/'
    | '/categories'
    | '/leaderboard'
    | '/projects'
    | '/freelancers/$id'
    | '/freelancers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriesRoute: typeof CategoriesRoute
  LeaderboardRoute: typeof LeaderboardRoute
  ProjectsRoute: typeof ProjectsRoute
  FreelancersIdRoute: typeof FreelancersIdRoute
  FreelancersIndexRoute: typeof FreelancersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelancers/': {
      id: '/freelancers/'
      path: '/freelancers'
      fullPath: '/freelancers/'
      preLoaderRoute: typeof FreelancersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelancers/$id': {
      id: '/freelancers/$id'
      path: '/freelancers/$id'
      fullPath: '/freelancers/$id'
      preLoaderRoute: typeof FreelancersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriesRoute: CategoriesRoute,
  LeaderboardRoute: LeaderboardRoute,
  ProjectsRoute: ProjectsRoute,
  FreelancersIdRoute: FreelancersIdRoute,
  FreelancersIndexRoute: FreelancersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
